namespace: playground

istio:
  enabled: true

frontend:
  image: bdjordjevic/msgnc-travel-frontend
  type: ClusterIP
  port: 80
  replicas: 1
  resources:
    requests:
      memory: 256Mi
backend:
  image: bdjordjevic/msgnc-travel
  type: ClusterIP
  port: 8080
  replicas: 1
  resources:
    requests:
      memory: 256Mi

pullPolicy: Always

nameOverride: "msgnc-travel"
fullnameOverride: "msgnc-travel"

deployment:
  backend:
    containerPort: 8080
  readinessProbe: /actuator/health
  livenessProbe: /actuator/health

kymaGateway:
  enabled: true
  hostname: msgnc-travel-app

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
    - chart-example.local
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}
